version: '3'


services:
  salt-master:
    image: cri/salt-master
    ports:
      - "4505:4505"
      - "4506:4506"
    volumes:
      - .:/srv/salt
      - ./etc:/etc/salt
    build:
      context: .
